spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: pass
    password: pass

  sql:
    init:
      mode: always


  h2.console.enabled: true
  jpa.defer-datasource-initialization: true
  jpa.hibernate.ddl-auto: update
  jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jpa.properties.hibernate.format_sql: true
  jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy